<?php
/**
 * Language labels for database tables/fields belonging to extension 'dr_blob'
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'tx_drblob_content' => 'Add new Document',	
		'tx_drblob_content.title' => 'Title',	
		'tx_drblob_content.description' => 'Description',	
		'tx_drblob_content.cruser_id' => 'Author',
		'tx_drblob_content.crdate' => 'Create Date',
		'tx_drblob_content.tstamp' => 'Last Change',
		'tx_drblob_content.blob_name' => 'Filename',	
		'tx_drblob_content.blob_size' => 'Filesize',	
		'tx_drblob_content.blob_type' => 'Filetype',	
		'tx_drblob_content.blob_data' => 'File',
		'tx_drblob_content.is_vip' => 'VIP-Record?',
		'tx_drblob_content.is_vip.desc' => 'Shall this record be shown in a vip-list?',
		'tt_content.list_type_pi1' => 'Filelist',	
		'tt_content.pi_flexform.sheet.datasource' => 'Data Source',
		'tt_content.pi_flexform.sheet.settings' => 'Settings',
		'tt_content.pi_flexform.whatToDisplay' => 'What shall be displayed:',
		'tt_content.pi_flexform.whatToDisplay.top' => 'TOP: List of VIP-items',
		'tt_content.pi_flexform.whatToDisplay.list' => 'LIST: List of items',
		'tt_content.pi_flexform.whatToDisplay.single' => 'SINGLE: Single item',
		'tt_content.pi_flexform.whatToDisplay.search' => 'SEARCH: Search items',
		'tt_content.pi_flexform.whatToDisplay.personal.list' => 'PERSONAL: Personalizable list',
		'tt_content.pi_flexform.whatToDisplaypersonal.add' => 'Show "Add to Personal Container" (LIST-Mode):',
		'tt_content.pi_flexform.limit' => 'Number of items to list:',
		'tt_content.pi_flexform.recursive' => 'Recursive:',
		'tt_content.pi_flexform.listOrderBy' => '"Order by" this field (LIST-Mode):',
		'tt_content.pi_flexform.listOrderBy.title' => 'Title',
		'tt_content.pi_flexform.listOrderBy.createdate' => 'Date of the creation',
		'tt_content.pi_flexform.listOrderBy.lastchange' => 'Date of the last change',
		'tt_content.pi_flexform.listOrderBy.author' => 'Author',
		'tt_content.pi_flexform.listOrderDirection' => 'Ascending or Descending:',
		'tt_content.pi_flexform.listOrderDirection.asc' => 'Ascending',
		'tt_content.pi_flexform.listOrderDirection.desc' => 'Descending',
		'tt_content.pi_flexform.template_file' => 'Template file:',
		'tt_content.pi_flexform.singlePID' => 'Page where to display single items:',
		'tt_content.pi_flexform.returnPID' => 'Page where to return to:',
	),
	'de' => Array (
		'tx_drblob_content' => 'Neues Dokument anlegen',		
		'tx_drblob_content.title' => 'Titel',	
		'tx_drblob_content.description' => 'Beschreibung',
		'tx_drblob_content.cruser_id' => 'Autor',
		'tx_drblob_content.crdate' => 'Erstelldatum',
		'tx_drblob_content.tstamp' => 'Letzte Änderung',
		'tx_drblob_content.blob_name' => 'Dateiname',	
		'tx_drblob_content.blob_size' => 'Dateigröße',	
		'tx_drblob_content.blob_type' => 'Dateityp',	
		'tx_drblob_content.blob_data' => 'Datei auswählen',
		'tx_drblob_content.is_vip' => 'Soll der Datensatz in einer VIP-Liste aufgeführt werden?',
		'tx_drblob_content.sort.asc' => 'Aufsteigend',
		'tx_drblob_content.sort.desc' => 'Absteigend',
		'tt_content.list_type_pi1' => 'Dateiliste',
		'tt_content.pi_flexform.sheet.datasource' => 'Datenquelle',
		'tt_content.pi_flexform.sheet.settings' => 'Einstellungen',
		'tt_content.pi_flexform.whatToDisplay' => 'Was soll angezeigt werden:',
		'tt_content.pi_flexform.whatToDisplay.top' => 'TOP: Liste bestehend aus VIP-Dokumenten',
		'tt_content.pi_flexform.whatToDisplay.list' => 'LIST: Liste aller Dokumente',
		'tt_content.pi_flexform.whatToDisplay.single' => 'SINGLE: Einzelnes Dokument',
		'tt_content.pi_flexform.whatToDisplay.search' => 'SEARCH: Suchen von Dokumenten',
		'tt_content.pi_flexform.whatToDisplay.personal.list' => 'PERSONAL: Personalisierbare Liste',
		'tt_content.pi_flexform.whatToDisplaypersonal.add' => '"Zu Persönlichen Container hinzufügen" anzeigen (LIST-Mode):',
		'tt_content.pi_flexform.limit' => 'Anzahl der Dokumente im LIST-, PERSONAL-Modus und im TOP-Modus:',
		'tt_content.pi_flexform.recursive' => 'Recursion:',
		'tt_content.pi_flexform.listOrderBy' => '"Sortiere nac" diesem Feld (LIST-Modus):',
		'tt_content.pi_flexform.listOrderBy.title' => 'Titel',
		'tt_content.pi_flexform.listOrderBy.createdate' => 'Erstelldatum',
		'tt_content.pi_flexform.listOrderBy.lastchange' => 'Letzte Änderung',
		'tt_content.pi_flexform.listOrderBy.author' => 'Autor',
		'tt_content.pi_flexform.listOrderDirection' => 'Aufsteigend oder Absteigend:',
		'tt_content.pi_flexform.listOrderDirection.asc' => 'Aufsteigend',
		'tt_content.pi_flexform.listOrderDirection.desc' => 'Absteigend',
		'tt_content.pi_flexform.template_file' => 'Template Datei:',
		'tt_content.pi_flexform.singlePID' => 'Seite auf der der Datensatz angezeigt wird:',
		'tt_content.pi_flexform.returnPID' => 'Seite zu der zurück gekehrt werden soll:',
	),
);
?>